## Домашнее задание № 1

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
X = np.arange(0, N)
Y = np.flip(X, 0)
Y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
matrix_value = np.diag(Y)
matrix_value

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

След матрицы – это сумма всех элементов в диагонали матрицы.

In [4]:
diagonal_values = np.trace(matrix_value)
diagonal_values

45

### Задание 3
Решите систему уравнений: <br />
4x + 2y + z = 4 <br />
x + 3y = 12 <br />
5y + 4z = -3 <br />

In [5]:
from numpy import linalg

In [6]:
# левая часть уравнения:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
a

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [7]:
# правая часть уравнения:
b = np.array([4, 12, -3])
b

array([ 4, 12, -3])

In [8]:
# вычисление:
result = linalg.solve(a, b)
result

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:

# проверка:
np.allclose(np.dot(a, result), b)

True

### Задание 4
Имеется матрица покупок в интернет-магазине. <br />
Столбец А - ID пользователя. <br />
Остальные столбцы - количество покупок категорий товаров этим пользователем: <br />


Матрица в виде numpy array:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

#### Решение:
Нам необходимо сравнить next_user_stats с каждым пользователем в матрице. Для этого, из матрицы необходимо извлечь каждого пользователя и в моменте сравнить с next_user_stats. Т.е.: <br />
* создаём цикл
* внутри цикла производим сравнение
* куда-то временно записываем результат
* выбираем max полученное значение

In [12]:
def cosine_angle (a, b):
    # для вычисления косинусного угла необходимо выполнить 3 действия:
        # найти скаляное произведение векторов
        # найти длину векторов
        # вычислить угол

    # вычисляем скалярное произведение 2-х векторов:
    scalar_product = np.dot(a, b)
    
    # вычисляем длину каждого вектора:
    aLen = np.linalg.norm(a)
    bLen = np.linalg.norm(b)

    # вычисляем косинус угла:
    cosine_angle = scalar_product / (aLen * bLen)

    return cosine_angle

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [27]:
# создаём словарь, в который будем записывать результаты:
user_similarity = {}

# создаём цикл, в котором будем сравнивать пользователей
# в цикле используем enumerate(users_stats), чтобы автоматом нумеровать
# каждый users_stats:
for id, user_param in enumerate(users_stats):
        # print(str(id) + " " + str(user_param))
    # находим значение косинусного угла сравнивая каждого пользователя
    # c новым:
    cosine_angle_value = cosine_angle(user_param, next_user_stats)
    # записываем id и значение каждой итерации в словарь
    user_similarity[id+1] = cosine_angle_value

print(user_similarity)

{1: 0.19999999999999996, 2: 0.8451542547285165, 3: 0.3999999999999999, 4: 0.7905694150420948, 5: 0.3999999999999999, 6: 0.0, 7: 0.0, 8: 0.9486832980505138, 9: 0.0, 10: 0.0}


In [30]:
# находим id максимально схожего пользователя:
max_similarity_user = max(user_similarity, key=user_similarity.get)
print(max_similarity_user)

8
