## Домашнее задание № 1

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [3]:
N = 10
X = np.arange(0, N)
Y = np.flip(X, 0)
Y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
matrix_value = np.diag(Y)
matrix_value

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

След матрицы – это сумма всех элементов в диагонали матрицы.

In [5]:
diagonal_values = np.trace(matrix_value)
diagonal_values

45

### Задание 3
Решите систему уравнений: <br />
4x + 2y + z = 4 <br />
x + 3y = 12 <br />
5y + 4z = -3 <br />

In [6]:
from numpy import linalg

In [7]:
# левая часть уравнения:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
a

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [8]:
# правая часть уравнения:
b = np.array([4, 12, -3])
b

array([ 4, 12, -3])

In [9]:
# вычисление:
result = linalg.solve(a, b)
result

array([ 0.46666667,  3.84444444, -5.55555556])

In [10]:

# проверка:
np.allclose(np.dot(a, result), b)

True

### Задание 4
Имеется матрица покупок в интернет-магазине. <br />
Столбец А - ID пользователя. <br />
Остальные столбцы - количество покупок категорий товаров этим пользователем: <br />


Матрица в виде numpy array:

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [14]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [23]:
# понятия не имею как решать эту задачу
# начну с того, что меня смущает отсутвияе User ID,
# буду индексировать динамически

# находим кол-во строк в матрице:
users_count = users_stats.shape[0]
# создаю массив с ID пользователей
user_id = np.arange(1, users_count+1)
user_id

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])